# Generated by Django 4.2.6 on 2023-10-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstiPro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pic'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(default='STUDENT', max_length=50),
        ),
    ]
