# Generated by Django 4.2.6 on 2023-10-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstiPro', '0004_student_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='ravi', max_length=100),
        ),
    ]
