# Generated by Django 4.2.6 on 2023-10-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstiPro', '0005_student_student_email_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_password',
            field=models.CharField(default=12345678, max_length=50),
        ),
    ]
