# Generated by Django 4.2.6 on 2023-10-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstiPro', '0006_student_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(default='Ravi', max_length=255),
        ),
    ]
