# Generated by Django 4.2.6 on 2023-10-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstiPro', '0007_remove_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_image',
        ),
    ]
