# Generated by Django 4.2.6 on 2023-10-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstiPro', '0009_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default='sarab', max_length=255),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='kaur', max_length=255),
        ),
        migrations.AddField(
            model_name='staff',
            name='mobile_number',
            field=models.CharField(default=1234567890, max_length=15),
        ),
        migrations.AddField(
            model_name='staff',
            name='student_email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='staff',
            name='student_password',
            field=models.CharField(default=12345678, max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(default='Ravi', max_length=255),
        ),
    ]
