# Generated by Django 4.2.6 on 2023-10-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstiPro', '0010_staff_first_name_staff_last_name_staff_mobile_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='student_email',
            new_name='staff_email',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='student_password',
            new_name='staff_password',
        ),
    ]
