# Generated by Django 4.2.6 on 2023-11-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstiPro', '0013_staff_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(default='HOD', max_length=50),
        ),
    ]
