# Generated by Django 4.2.6 on 2023-11-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstiPro', '0015_staff_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_leave',
            name='date',
        ),
        migrations.AddField(
            model_name='staff_leave',
            name='end_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff_leave',
            name='start_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
