# Generated by Django 4.2.6 on 2023-11-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstiPro', '0016_remove_staff_leave_date_staff_leave_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_notification',
            name='message',
            field=models.TextField(default='Hello'),
        ),
        migrations.AddField(
            model_name='staff_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
